Feature 3
Javivy/hello-microverse pull request #2
Opened 2022-08-16 20:39 UTC by Javivy

Add linters
Create HTML and CSS file
Create .gitignore

2022-08-16 21:19 UTC, Kamba56 requested changes
Hi @Javivy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![SoCloseKeeganMichaelKeyGIF](https://user-images.githubusercontent.com/94551484/184984891-9c95be55-840b-49b6-b9af-434cfc6f04d6.gif)

## Highlights

- [ ] Meaningful commit messages
- [ ] All linters checks passed
- [ ] Descriptive summary of pull request

## Required Changes ♻️
- [ ] Please edit your `README.md` file to be more descriptive. This will make your repo more professional.
- [ ] Kindly edit your pull request title. The pull request title should be descriptive, describing the implemented change. You can edit the pull request title by clicking the `edit` button next to it.

_Check the comments under the review for more changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [Optional] Kindly change the name of your branch to a [feature or action](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md#feature-branches) to make your work look more professional. You can rename your branch by following [this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) steps.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 21:19 UTC, Kamba56 commented on .github/workflows/linters.yml
> +          npm install --save-dev hint@7.x
- [ ] Kindly setup webhint correctly. Please copy the files from [this](https://github.com/microverseinc/linters-config/tree/master/html-css) repo into your repository and run `npm install --dave-dev hint@7.x` in your terminal. Please do not delete the `package.lock.json`, `package.json` and `.hintrc` files.

2022-08-16 21:19 UTC, Kamba56 commented on .github/workflows/linters.yml
> +          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
- [ ] Kindly set up stylelint correctly. Please copy the files from [this](https://github.com/microverseinc/linters-config/tree/master/html-css) repo into your repository and run ` npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x` in your terminal. Please do not delete the `package.lock.json`, `package.json`, and `.stylelintrc.json` files.

2022-08-17 15:36 UTC, topeogunleye approved these changes
### Hi @Javivy, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
 
## [Optional] suggestions:
>- [ ] Next time, and for future Pull Requests, please kindly add a more descriptive PR title.
> See a demo below:
![pull_request_desc](https://user-images.githubusercontent.com/52934128/177452738-0610c008-a53a-454e-8aac-635cb4ed812c.gif)

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 16:03 UTC, merged